### ISSUE TITLE
Volcaddons Randomly Stops Working

### ISSUE THREAD

**Issue by crazeeey** [zhenga8533/VolcAddons#1]
When I use this mod it sometimes randomly stops working and I dont know how to fix it. None of my HUD and Kuudra mods show up and even when I restart it ahs not fixed itself. This has happened multiple times now and it makes my QOL in Kuudra and Crimson Isles hell. Please try to fix this bug.

**Comment by zhenga8533** [comment]
this should be fixed (theoretically)

**Comment by crazeeey** [comment]
Well it wasn't :( check around on discord servers and a lot of people are having this issue.

**Comment by zhenga8533** [comment]
the GitHub one has been working as of now, but the CT one has not updated. I know that there is some mod conflict with Dulkir/DSM mod, but not too sure on the specific details on that.
